### ISSUE TITLE
Вкладка "Выгрузки ..." и "Проверкb ..." выдают ошибки

### ISSUE THREAD

**Issue by dserov** [orgtechservice/roskombox#14]
Текст ошибки:
`KeyError at /downloads

'request'

Request Method:     GET
Request URL:    http://roskombox.local:8000/downloads
Django Version:     1.10
Exception Type:     KeyError
Exception Value:    

'request'

Exception Location:     /home/admin/venvs/roskombox/lib/python3.4/site-packages/django/template/context.py in **getitem**, line 75
Python Executable:  /usr/bin/uwsgi-core
Python Version:     3.4.2
Python Path:    

['.',
 '',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/home/admin/venvs/roskombox/lib/python3.4/site-packages']

Server time:    Ср, 24 Авг 2016 14:09:58 +0300`

**Comment by WST** [comment]
Сообщите, пожалуйста, версии зависимостей, установленные в виртуальное окружение (pip list или pip freeze при активированном виртуаленве).

**Comment by dserov** [comment]
Запрошенная информация.
`(roskombox) admin@xbtt:~$ pip list

Django (1.10)
django-bootstrap-pagination (1.6.2)
django-crispy-forms (1.6.0)
django-jsonview (1.0.0)
django-sendmail-backend (0.1.2)
lxml (3.6.4)
mysqlclient (1.3.7)
pip (1.5.6)
requests (2.11.1)
rrdtool (0.1.5)
setuptools (5.5.1)
suds-py3 (1.3.2.0)
uwsgidecorators (1.1.0)
`

**Comment by WST** [comment]
Попробуйте в качестве workaround пока сделать даунгрейд джанги следующим образом: при активированном виртуальном окружении выполните следующие команды:

```
pip uninstall Django
pip install Django==1.9.4
```

Сообщите, присутствует ли проблема после таких манипуляций.

**Comment by dserov** [comment]
Да, спасибо. Заработало!

**Comment by WST** [comment]
Я, наверное, не буду пока на 1.10.х проект переводить, сегодня немного потестирую с последней версией в ветке 1.9 — 1.9.9, если всё нормально будет работать, отпишусь здесь, можно будет обновиться. Согласно [официальному сайту](https://www.djangoproject.com/download/), уже через несколько месяцев выйдет версия 1.11, это будет LTS (long time support) версия, тогда и займусь правками кода для совместимости с ней.

**Comment by WST** [comment]
Да, можно смело обновляться до 1.9.9. Обновление Django можно произвести так, как показано выше. Обновление самого Roskombox производится следующим образом (при активированном виртуальном окружении):

```
git pull
./manage.py migrate
./manage.py collectstatic
service uwsgi-emperor restart
```

Оставшиеся пожелания сегодня не успеваю, ориентировочно в понедельник.
